### PR TITLE
[AS-90] Toolbar is mocked

### PR DESCRIPTION
**Pull request by mslup**

### CODE REVIEW

**Comment by andrmdmd** [comment]
1. What is the purpose of adding this placeholder instead of leaving empty space?
2. Opening both controls causes unintended behavior
image

**Comment by mslup** [comment]
> 1. What is the purpose of adding this placeholder instead of leaving empty space?

no particular reason, it doesn't make a difference since it will be overridden anyway, I wanted to have a visual clue that something is going to be there

> 2. Opening both controls causes unintended behavior

yes, this will be addressed in a future pull request, the scope of this one was to just provide a mocked div structure for the toolbar

**Comment by andrmdmd** [comment]
> > 1. What is the purpose of adding this placeholder instead of leaving empty space?
> 
> no particular reason, it doesn't make a difference since it will be overridden anyway, I wanted to have a visual clue that something is going to be there
> 
> > 2. Opening both controls causes unintended behavior
> 
> yes, this will be addressed in a future pull request, the scope of this one was to just provide a mocked div structure for the toolbar 
> 
> 
> 

Okay, I leave all "non-final" toolbar decisions/opinionsb (like approving this PR) to you and @GitQueenZofia then as you will know what will be helpful for your cooperation

**Review by GitQueenZofia — APPROVED** [review]
ok 👍

**Pull request merged**
